### ISSUE TITLE
Can you better explain how the program works (documentation) ?

### ISSUE THREAD

**Issue by anahibemol** [thinker227/BestPracticeAnalyzer#1]
Hello, I got interested in the project but can't really understand how it works just from the ReadMe alone, can you improve your documentation, if possible ?

**Comment by thinker227** [comment]
I apologize but this project is a joke mainly intended to poke fun at enterprise developers. The analyzer reports a warning on every line stating "Consider whether this code is adhering to best practices". If you're curious about writing Roslyn analyzers, check out [Getting started with Roslyn analyzers](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers?view=vs-2022) from the MSDN, or just poke into the code of this project as it's just a really simple analyzer.

**Comment by anahibemol** [comment]
Oh ok

I thought it was more about C# due to the language recognition tagging of Github.

Thought it was still a early project jugding by the size and wanted to give some advice but that's ok, I get the necessity of this kind of satire for the dev world.
